name: CI

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'NetKit/**'
      - '.github/workflows/**'
      - '**.podspec'
      - 'Package.swift'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print
      run: ls -al
    - name: Updating CocoaPods repo
      run: pod repo update
    - name: Pod linting
      run: pod lib lint --fail-fast --verbose
      
